In [1]:
import numpy as np

In [21]:
k = 100
d = 3
active_arms01 = np.random.binomial(n=1, p=0.1, size=k)
active_arms = np.where(active_arms01 == 1)[0]
print(active_arms)

[22 23 36 41 46 48 70 78 79 81 83 94]


In [10]:
def make_smaller_matrix(A, active_arms):
    B = np.zeros((len(active_arms),A.shape[1]))

    for i in range(len(active_arms)):
        B[i,:] = A[active_arms[i],:]

    return B

In [57]:
A = np.random.normal(size=(k,d))

In [58]:
B = make_smaller_matrix(A, active_arms)

In [68]:
def compute_induced_norm(Ainv, v):
    results = np.zeros(v.shape[0])
    for i in range(v.shape[0]):
        results[i] = np.dot(v[i,:].T, np.dot(Ainv, v[i,:]))
    return results

def compute_design_matrix(A, pi):
    D = np.zeros((A.shape[1],A.shape[1]))

    for i in range(A.shape[1]):
        D += pi[i]*np.dot(A[i:i+1,:].T,A[i:i+1,:])
    return D

def onehot(idx, k):
    v = np.zeros(k)
    v[idx] = 1
    return v



def find_optimal_design(A, iter=10):
    k = A.shape[0]
    pi = np.ones(k)/k

    for it in range(iter):
        D = compute_design_matrix(A, pi)
        Dinv = np.linalg.inv(D)
        v = compute_induced_norm(Dinv, A)

        best_index = np.argmax(v)
        current = v[best_index]
        print(Dinv)
        print(A[best_index])
        gamma = (current/d-1)/(current-1)

        pi = (1-gamma)*pi + gamma*onehot(best_index, k)
        # print(pi)

    return 

In [69]:
find_optimal_design(B)

[[15.85201553 23.59519798  7.66502448]
 [23.59519798 41.55447795 11.76943277]
 [ 7.66502448 11.76943277  6.31968102]]
[0.08273748 0.98111917 2.14192313]
[[23.58797584 35.10991764 11.40564188]
 [35.10991764 61.83352646 17.51304717]
 [11.40564188 17.51304717  9.40375582]]
[0.08273748 0.98111917 2.14192313]
[[35.1919163  52.38199714 17.01656798]
 [52.38199714 92.25209922 26.12846877]
 [17.01656798 26.12846877 14.02986801]]
[0.08273748 0.98111917 2.14192313]
[[ 52.59782698  78.29011638  25.43295713]
 [ 78.29011638 137.87995837  39.05160118]
 [ 25.43295713  39.05160118  20.9690363 ]]
[0.08273748 0.98111917 2.14192313]
[[ 78.70669301 117.15229524  38.05754085]
 [117.15229524 206.32174708  58.43629978]
 [ 38.05754085  58.43629978  31.37778873]]
[0.08273748 0.98111917 2.14192313]
[[117.86999206 175.44556353  56.99441643]
 [175.44556353 308.98443015  87.51334769]
 [ 56.99441643  87.51334769  46.99091738]]
[0.08273748 0.98111917 2.14192313]
[[176.61494063 262.88546597  85.3997298 ]
 [262.8854659